version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/coinbase/odin
    steps:
      - checkout
      - run: export GO111MODULE=on && go mod download
      - run: export GO111MODULE=on && go test ./...

